# Generated by Django 4.2.3 on 2023-07-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Relationship_description', models.CharField(max_length=100)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='Users.user')),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_managed', to='Users.user')),
            ],
        ),
    ]
