# Generated by Django 4.2.4 on 2023-08-17 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_user_is_hr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ID',
            new_name='id',
        ),
    ]
