# Generated by Django 4.2.4 on 2023-08-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_boarding_request',
            name='job_experience',
        ),
        migrations.AddField(
            model_name='experience',
            name='onboarding_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Onboarding.on_boarding_request'),
            preserve_default=False,
        ),
    ]
