# Generated by Django 4.2.4 on 2023-08-16 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Onboarding', '0002_remove_on_boarding_request_job_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='on_boarding_request',
            options={'verbose_name': 'On-Boarding Request', 'verbose_name_plural': 'On-Boarding Requests'},
        ),
        migrations.AddField(
            model_name='on_boarding_request',
            name='Assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='on_boarding_request',
            name='HR_comment',
            field=models.TextField(null=True, verbose_name='HR Comment'),
        ),
        migrations.AddField(
            model_name='on_boarding_request',
            name='Status',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject '), ('PENDING', 'Pending')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='on_boarding_request',
            name='Technical_comment',
            field=models.TextField(null=True, verbose_name='Technical Comment'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='onboarding_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='Onboarding.on_boarding_request'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='application_date',
            field=models.DateField(verbose_name='Application Date'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='current_employer_benefits',
            field=models.TextField(verbose_name='Current Employer Benefits'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='education',
            field=models.TextField(verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='expected_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Expected Salary'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='father_occupation',
            field=models.CharField(max_length=100, verbose_name='Father Occupation'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='marital_status',
            field=models.CharField(choices=[('married', 'Married'), ('divorced', 'Divorced'), ('single', 'Single')], max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='military_service',
            field=models.CharField(choices=[('exempted', 'Exempted'), ('serving', 'Serving'), ('postponed', 'Postponed')], max_length=50, verbose_name='Military Service'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='notice_period',
            field=models.CharField(max_length=20, verbose_name='Notice Period'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='num_of_kids',
            field=models.PositiveIntegerField(verbose_name='Number of Kids'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='place_of_birth',
            field=models.CharField(max_length=100, verbose_name='Place of Birth'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='position_applying_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onboarding.position', verbose_name='Position Applying For'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='references',
            field=models.TextField(verbose_name='References'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='referred_by',
            field=models.CharField(max_length=50, verbose_name='Referred By'),
        ),
        migrations.AlterField(
            model_name='on_boarding_request',
            name='spouse_occupation',
            field=models.CharField(max_length=100, verbose_name='Spouse Occupation'),
        ),
    ]
