# Generated by Django 4.2.4 on 2023-08-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0003_alter_on_boarding_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='on_boarding_request',
            name='Status',
            field=models.CharField(choices=[('ACCEPT', 'ACCEPT'), ('REJECTED', 'REJECTED'), ('Awaiting HR Approval', 'Awaiting HR Approval'), ('Awaiting Supervisor Approval', 'Awaiting Supervisor Approval')], default='Awaiting HR Approval', max_length=50, verbose_name='Status'),
        ),
    ]
