# Generated by Django 4.2.4 on 2023-08-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboarding', '0004_alter_on_boarding_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='on_boarding_request',
            name='Rejection_reason',
            field=models.TextField(null=True, verbose_name='Rejection Reason'),
        ),
    ]
